In [1]:
import numpy as np

In [7]:
a=np.zeros((1,5))
print(a)
print(a.dtype)
print(a.shape)
print(a.size)

[[0. 0. 0. 0. 0.]]
float64
(1, 5)
5


In [9]:
a=np.ones((1,5,4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [11]:
print(np.arange(1,21).reshape(4,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [32]:
a=np.arange(1,21).reshape(4,5)
b=a*10
print(b)#array multiple of 10
print(a[a%2!=0]) #odd numbers

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]
[ 1  3  5  7  9 11 13 15 17 19]


In [25]:
a= np.arange(1, 21) .reshape(4,5)
a[a%2==0] *= -1          
print (a)

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [43]:
M1=np.arange(1,17).reshape(4,4)
print(M1)#4*4 matrix

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [44]:
M1=np.arange(1,17).reshape(4,4)
M2=M1.T
print(M2)#transpose matrix

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [45]:
M1=np.arange(1,17).reshape(4,4)
M2=M1.T
M3=M1+M2
print(M3)#sum of M1 and M2

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [46]:
#Find Transpose of M3, Call it MT1. Check if M3 == MT1
M1=np.arange(1,17).reshape(4,4)
M2=M1.T
M3=M1+M2
MT1=M3.T
print(M3==MT1)   

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [47]:
#find diffrence of M4 = (M1 - M2)
M1=np.arange(1,17).reshape(4,4)
M2=M1.T
M4=M1-M2
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [51]:
#Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
M1=np.arange(1,17).reshape(4,4)
M2=M1.T
M4=M1-M2
MT2=M4.T
print(M4==MT2)
print(M4==-MT2)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [58]:
#create a matrix (3x4) R1 of random numbers between 10-40
from numpy import random
r1=random.randint(10,40,size=(3,4))
print(r1)

[[16 18 33 26]
 [23 14 34 29]
 [25 14 38 37]]


In [62]:
#find min and max column wise
from numpy import random
r1=random.randint(10,40,size=(3,4))
print(r1)
print(r1.min(0))#min column
print(r1.max(0))#max column

[[27 22 39 29]
 [10 13 37 16]
 [21 32 36 21]]
[10 13 36 16]
[27 32 39 29]


In [2]:
#replace the last column with sum of all the columns
from numpy import random
r1=random.randint(10,40,size=(3,4))
print(r1.sum(axis=1))
print(r1[:,3])
r1[:,3]=r1.sum(axis=1)
print()
print(r1)

[84 78 78]
[19 31 26]

[[12 32 21 84]
 [13 21 13 78]
 [10 29 13 78]]


In [101]:
#create a matrix (3x4) R1 of random numbers between 10-40
r1=random.randint(10,40,size=(3,4))
print(r1)

[[37 19 23 14]
 [38 23 14 34]
 [31 18 34 37]]


In [119]:
#replace all even elements with nan in R1
r1=random.randint(10,40,size=(3,4))
r1=r1.astype("float")
r1[r1%2==0]=np.NaN
print(r1)

[[nan nan 39. 15.]
 [11. 35. nan 39.]
 [35. 35. 29. nan]]


In [128]:
#count number of nan in R1
r1=random.randint(10,40,size=(3,4))
r1=r1.astype("float")
r1[r1%2==0]=np.NaN
a=np.count_nonzero(np.isnan(r1))
print(r1)
print(a)

[[nan nan 39. 33.]
 [nan 11. nan 39.]
 [nan nan 29. nan]]
7


In [129]:
#output
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
