## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [1]:
import numpy as np

In [6]:
#create a numpy array of 5 zeros.
#check datatype, itemsize and shape of above

zer = np.zeros(5)
print(zer,type(zer))
print(zer.dtype)
print(zer.size)

[0. 0. 0. 0. 0.] <class 'numpy.ndarray'>
float64
5


In [9]:
# create a numpy array of ones of shape (5,4)

one = np.ones((5,4))
print(one)
print(one.size)
print(one.shape)
print(one.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
20
(5, 4)
float64


In [14]:
# create a matrix of shape 4,5 with numbers from 1-20
dat = np.arange(1,21).reshape((4,5))
print(dat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
# multiply all elements of above array by 10
dat1 = dat * 10
print(dat1)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [48]:
# print odd elements from array - question unable to understand
print(dat[dat%2==1])

[ 1  3  5  7  9 11 13 15 17 19]


In [57]:
#replace all even elements by their negative
dat%2==0
np.where( dat%2==0,dat*-1,dat)

array([[  1,  -2,   3,  -4,   5],
       [ -6,   7,  -8,   9, -10],
       [ 11, -12,  13, -14,  15],
       [-16,  17, -18,  19, -20]])

In [62]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

M1 = np.linspace(1,16,16).reshape(4,4)
print(lin)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [63]:
# create a transpose of above matrix call it M2
M2 = M1.T
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [64]:
# find sum of above matrix M3 = (M1 + M2)
M3 = M1 + M2
print(M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [66]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.T
M3 == MT1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [67]:
# find diffrence of M4 = (M1 - M2)
M4 = M1 - M2
print(M4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [69]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = M4.T
print(MT2== M4)
print()
print(-MT2== M4)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [90]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,size=(3,4))
print(R1)

[[28 21 29 23]
 [10 18 30 18]
 [23 15 22 29]]


In [91]:
# find min and max column wise
mn = np.min(R1,axis=1)
print(mn)
mx =np.max(R1,axis=1)
print(mx)

[21 10 15]
[29 30 29]


In [97]:
# replace the last column with sum of all the columns
R1[-1] = R1.sum(axis=0)
print(R1)

[[28 21 29 23]
 [10 18 30 18]
 [61 54 81 70]]


In [99]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1 =  np.random.randint(10,40,size=(3,4))
print(R1)

[[19 13 22 10]
 [37 34 26 17]
 [26 25 38 19]]


In [113]:
# replace all even elements with nan in R1
R1 = np.where(R1%2==0,np.nan,R1)
print(R1)

[[19. 13. nan nan]
 [37. nan nan 17.]
 [nan 25. nan 19.]]


C:\Users\kosreddy\AppData\Local\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in remainder
  


In [114]:
# count number of nan in R1
np.isnan(R1).sum()

6

## Check the output

In [118]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
