In [3]:
# all imports go at the top, even though python is a very open language
import pandas as pd
import numpy as np

In [55]:
help(pd.read_sql)

Help on function read_sql in module pandas.io.sql:

read_sql(sql, con, index_col=None, coerce_float=True, params=None, parse_dates=None, columns=None, chunksize=None)
    Read SQL query or database table into a DataFrame.
    
    This function is a convenience wrapper around ``read_sql_table`` and
    ``read_sql_query`` (for backward compatibility). It will delegate
    to the specific function depending on the provided input. A SQL query
    will be routed to ``read_sql_query``, while a database table name will
    be routed to ``read_sql_table``. Note that the delegated function might
    have more specific notes about their functionality not listed here.
    
    Parameters
    ----------
    sql : string or SQLAlchemy Selectable (select or text object)
        SQL query to be executed or a table name.
    con : SQLAlchemy connectable (engine/connection) or database string URI
        or DBAPI2 connection (fallback mode)
    
        Using SQLAlchemy makes it possible to use any DB

In [13]:
print(dir(pd))

['Categorical', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'ExcelFile', 'ExcelWriter', 'Expr', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int64Index', 'Interval', 'IntervalIndex', 'MultiIndex', 'NaT', 'Panel', 'Period', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseArray', 'SparseDataFrame', 'SparseSeries', 'Term', 'TimeGrouper', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt64Index', 'WidePanel', '_DeprecatedModule', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_hashtable', '_lib', '_libs', '_np_version_under1p10', '_np_version_under1p11', '_np_version_under1p12', '_np_version_under1p13', '_np_version_under1p14', '_np_version_under1p15', '_tslib', '_version', 'api', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'datetime', 'datetools', 'describe_option', 'errors', 'eval', 'factorize', 'get_dummies', 'get_opt

In [14]:
print(dir(pd.DataFrame))

['T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '_AXIS_SLICEMAP', '__abs__', '__add__', '__and__', '__array__', '__array_wrap__', '__bool__', '__bytes__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ro

In [15]:
print(dir(pd.Series))

['T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '_AXIS_SLICEMAP', '__abs__', '__add__', '__and__', '__array__', '__array_prepare__', '__array_priority__', '__array_wrap__', '__bool__', '__bytes__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__

## Series

In [4]:
# Normal series and series with custom index
s1 = pd.Series([1,2,3])
s2 = pd.Series([1,2,3, np.nan], index=list("abcd"))
print(s1)
print()
print(s2)

0    1
1    2
2    3
dtype: int64

a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64


In [23]:
# changing dtype: astype
# before using astype we should make sure that there is no nan and nan == nan => False

r = s2
r = r.fillna(0)
r = r.astype(int)
print(r)

a    1
b    2
c    3
d    0
dtype: int32


In [19]:
# shape, size, dtype, index, values
print(s1.shape)
print(s1.size)
print(s1.dtype)
print(s1.values,type(s1.values))
print(s1.index)
print(type(s1.index))
print()

print(s2.shape)
print(s2.size)
print(s2.dtype)
print(s2.values,type(s2.values))
print(s2.index)
print(type(s2.index))

(3,)
3
int64
[1 2 3] <class 'numpy.ndarray'>
RangeIndex(start=0, stop=3, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>

(4,)
4
float64
[ 1.  2.  3. nan] <class 'numpy.ndarray'>
Index(['a', 'b', 'c', 'd'], dtype='object')
<class 'pandas.core.indexes.base.Index'>


In [27]:
# aggregate operations: min, max, unique, sum etc.
print(min(s1))
print(max(s1))
print(s1.unique())
print(sum(s1))
print()

print(min(s2))
print(max(s2))
print(s2.unique())
print(sum(s2))

1
3
[1 2 3]
6

1.0
3.0
[ 1.  2.  3. nan]
nan


In [32]:
# arithmetic operations(new copy) and broadcast like numpy
a = pd.Series([1,2,3,4])
b = pd.Series([5,6,7,8])
print(a+b)
print()
print(b-a)
print()
print(a*b)
print()
print(a/b)

0     6
1     8
2    10
3    12
dtype: int64

0    4
1    4
2    4
3    4
dtype: int64

0     5
1    12
2    21
3    32
dtype: int64

0    0.200000
1    0.333333
2    0.428571
3    0.500000
dtype: float64


In [36]:
# indexing and slicing
#boolean indexing
idx = s1%2 == 0
print(s1)
print(s1[idx])

c = np.arange(10)
idx = c%2 == 0
print(c[idx])

#slicing
s =  pd.Series(np.arange(10))
print()
print(s)
print()

0    1
1    2
2    3
dtype: int64
1    2
dtype: int64
[0 2 4 6 8]

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32


In [ ]:
# result of operations as index

In [41]:
# frequency : value_counts
print(s1)
print(s1.value_counts())

0    1
1    2
2    3
dtype: int64
3    1
2    1
1    1
dtype: int64


## DataFrame

In [45]:
# dataframe from dict or list of rows
df1 = pd.DataFrame(
    {
        "Name":   ["Gaurav", "Abhishek1", "Krishna", "Abhishek2", "Harshita", "Joey", "Shweta", "na-1" , "na-2"  , np.nan],
        "Age":    [ 0      , 1          , 2        , 2          , 1         , 2     , 3       , 1      ,  np.nan , 2     ],
        "Gender": [ 0      , 0          , 0        , 0          , 1         , 1     , 1       , np.nan ,  0      , 0     ]
    }
)
df2 = pd.DataFrame([("Gaurav",1), ("Abhiskek",2), ("Krishna",3), ("Abhishek2",4)],
                    index=[0,11,2,3], 
                    columns=["Name", "Number"])
print(df1)
print()
print(df2)
print(type(df2.columns))

        Name  Age  Gender
0     Gaurav  0.0     0.0
1  Abhishek1  1.0     0.0
2    Krishna  2.0     0.0
3  Abhishek2  2.0     0.0
4   Harshita  1.0     1.0
5       Joey  2.0     1.0
6     Shweta  3.0     1.0
7       na-1  1.0     NaN
8       na-2  NaN     0.0
9        NaN  2.0     0.0

         Name  Number
0      Gaurav       1
11   Abhiskek       2
2     Krishna       3
3   Abhishek2       4
<class 'pandas.core.indexes.base.Index'>


In [54]:
# shape, size, dtypes, index, columns, unique, T
print(df1.shape)
print(df1.size)
print(df1.dtypes)
print(type(df1.dtypes))
print(df1.index)
print(type(df1.index))
print(df1.columns)
print(type(df1.columns))
print(df1.T)

print()

print(df2.shape)
print(df2.size)
print(df2.dtypes)
print(type(df2.dtypes))
print(df2.index)
print(df2.columns)
print(df2.T)



(10, 3)
30
Name       object
Age       float64
Gender    float64
dtype: object
<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=10, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>
Index(['Name', 'Age', 'Gender'], dtype='object')
<class 'pandas.core.indexes.base.Index'>
             0          1        2          3         4     5       6     7  \
Name    Gaurav  Abhishek1  Krishna  Abhishek2  Harshita  Joey  Shweta  na-1   
Age          0          1        2          2         1     2       3     1   
Gender       0          0        0          0         1     1       1   NaN   

           8    9  
Name    na-2  NaN  
Age      NaN    2  
Gender     0    0  

(4, 2)
8
Name      object
Number     int64
dtype: object
<class 'pandas.core.series.Series'>
Int64Index([0, 11, 2, 3], dtype='int64')
Index(['Name', 'Number'], dtype='object')
            0         11       2          3 
Name    Gaurav  Abhiskek  Krishna  Abhishek2
Number       1         2        3          4


In [ ]:
# Rename index and columns on df2.
# Inplace vs normal operation


In [ ]:
# Indexing columns directly and via index. 

In [ ]:
# Series in a DataFrame

In [ ]:
# describe, top/bottom rows of data

In [ ]:
# indexing and slicing
# loc, iloc [rows, cols]

In [ ]:
# aggregate operations (with and without axis : row-1, col-0)
# min, max, count, ...

In [ ]:
# arithmetic operations

In [ ]:
# Na Values: isna, fillna, dropna

In [ ]:
# any, all

In [ ]:
# ordering data, sort_values

In [ ]:
# row / column wise operation: apply
tmp = pd.DataFrame(np.random.randint(10,20,20).reshape(5,4))

In [ ]:
# str submodule (replace etc)

In [ ]:
# load and save data

In [ ]:
# groups: groupby

In [ ]:
# groups and aggregates