### Numpy

In [ ]:
[1,2,3]

# [1010, 500, 5000]  1000
# 1010 1
# 500 2
# 5000 3

#a = []
#for i in range(len(a)):
#   a[i] += 1

# [1,2,3] => 4bytes
# 1000  1004   1008
# 1      2     3
# 1+1   2+1   3+1 => in shot

# numpy use C-arrays for storing data

In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [5]:
r = np.array([])
print(r, type(r))
print(dir(r))

[] <class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '

In [14]:
r = np.array([1,2,3])
print(r)
print(r.dtype)

print()
r = np.array((1.0,2,3))
print(r)
print(r.dtype)
print(r.ndim)
print(r.shape)
print(r.size)

print()
print(r.min(), r.max(), r.sum())

[1 2 3]
int64

[1. 2. 3.]
float64
1
(3,)
3

1.0 3.0 6.0


In [17]:
r = np.array([1,2,30000], dtype=np.int8)
print(r)
print(r.dtype)

# b4 b3 b2 b1
# .. .. .. ..
# endianness ...  b4 1000 b3 1001 b2 1002 ..
#    b1 1000 b2 1001 b3 1002 ...


r = np.array([1,2,300.55], dtype=np.int8)
print(r)
print(r.dtype)

[ 1  2 48]
int8
[ 1  2 44]
int8


In [ ]:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\arrayprint.py in _array2string(a, options, separator, prefix)
    508 
    509     # find the right formatting function for the array
--> 510     format_function = _get_format_function(data, **options)
    511 
    512     # skip over "["


In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

print(np.version)
print(np.__version__)

[1 2 3 4 5]
<class 'numpy.ndarray'>
<module 'numpy.version' from '/opt/anaconda3/lib/python3.8/site-packages/numpy/version.py'>
1.18.5


In [23]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=2)
print(arr)
print(type(arr))


[[1 2 3 4]]
<class 'numpy.ndarray'>


In [32]:
arr = np.array([[1, 2 ,0], [3, 4, 4]])
print(arr)

print()
print(arr.shape)
print(arr.size) # no of elements
print(arr.ndim)
print(arr.dtype)


[[1 2 0]
 [3 4 4]]

(2, 3)
6
2
int64


In [31]:
arr = np.array([[1, 2 ,0], [3, 4]])
print(arr)

print()
print(arr.shape)
print(arr.size) # no of elements
print(arr.ndim)
print(arr.dtype)

[list([1, 2, 0]) list([3, 4])]

(2,)
2
1
object


In [34]:
a = np.array( ((1,2,3),(3,2,1)), dtype='int16' )
print(a)


[[1 2 3]
 [3 2 1]]


In [37]:
a = np.arange(10, )
print(a)
a = np.arange(10, 100)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
int64


In [40]:
a = np.arange(12)
a = a.reshape(3,4)
print(a)

a = np.arange(12).reshape(3,3)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


ValueError: cannot reshape array of size 12 into shape (3,3)

In [46]:
# create a matrix like this
# 12 11 10
# 9  8  7
# ..
# 3  2  1 
r=np.arange(12,0,-1)
print(r)
r = r.reshape(4,3)
print(r)
r = r.reshape(3,4)
print(r)
r = r.reshape(12,1)
print(r)
# slicing , indexing

[12 11 10  9  8  7  6  5  4  3  2  1]
[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[12]
 [11]
 [10]
 [ 9]
 [ 8]
 [ 7]
 [ 6]
 [ 5]
 [ 4]
 [ 3]
 [ 2]
 [ 1]]


In [43]:
r=np.arange(12,0,-1).reshape(4,3)
print(r[0])
print(r[0][0])

[12 11 10]
12


In [44]:
r=np.arange(12,0,-1).reshape(4,3)
print(r[0])
print(r[0,0]) # index for row and column separated by ,

[12 11 10]
12


In [49]:
r=np.arange(12,0,-1).reshape(4,3)

print(r)

print()
print(r[0])
print(r[: , 0])

[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]

[12 11 10]
[12  9  6  3]


In [50]:
r=np.arange(12,0,-1)

print(r)

print()
print(r[0])
print(r[: , 0])

[12 11 10  9  8  7  6  5  4  3  2  1]

12


IndexError: too many indices for array

In [51]:
r=np.arange(12,0,-1).reshape(4,3)

print(r)

print()
print(r[1: , ::-1])

[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [59]:
r = np.random.randint(20, size=(3,4))
print(r)

b = r > 10
print(b)

[[ 5 16  7 16]
 [ 3  8 12 12]
 [12  6 12  4]]
[[False  True False  True]
 [False False  True  True]
 [ True False  True False]]


In [61]:
print(r)
print(r%2 == 0)
print(r**3)

[[ 5 16  7 16]
 [ 3  8 12 12]
 [12  6 12  4]]
[[False  True False  True]
 [False  True  True  True]
 [ True  True  True  True]]
[[ 125 4096  343 4096]
 [  27  512 1728 1728]
 [1728  216 1728   64]]


In [64]:
r1 = r//2 # scalar
r2 = r + 3
r3 = r1 + r2 # vector
print(r1)
print(r2)
print(r3)

z = np.zeros((3,3))
print(r1 + z)

[[2 8 3 8]
 [1 4 6 6]
 [6 3 6 2]]
[[ 8 19 10 19]
 [ 6 11 15 15]
 [15  9 15  7]]
[[10 27 13 27]
 [ 7 15 21 21]
 [21 12 21  9]]


ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [70]:
# boolean indexing

print(r)

d = r%2 == 0
print(d)

print()
print(r[d])
print(r[~d])
print(r[~d].sum())

[[ 5 16  7 16]
 [ 3  8 12 12]
 [12  6 12  4]]
[[False  True False  True]
 [False  True  True  True]
 [ True  True  True  True]]

[16 16  8 12 12 12  6 12  4]
[5 7 3]
15


In [72]:
# boolean indexing

print(r)

idx = r%2 == 0
e = r**2 # raise to power 2 for even no
print(e)
o = r//2 # divide odd ones by 2 
print(o)

print()
print(idx)
res = np.where(idx, e, o)
print(res)

res = np.where(idx)
print()
print(res)

[[ 5 16  7 16]
 [ 3  8 12 12]
 [12  6 12  4]]
[[ 25 256  49 256]
 [  9  64 144 144]
 [144  36 144  16]]
[[2 8 3 8]
 [1 4 6 6]
 [6 3 6 2]]

[[False  True False  True]
 [False  True  True  True]
 [ True  True  True  True]]
[[  2 256   3 256]
 [  1  64 144 144]
 [144  36 144  16]]

(array([0, 0, 1, 1, 1, 2, 2, 2, 2]), array([1, 3, 1, 2, 3, 0, 1, 2, 3]))


In [77]:
print()
print(idx)
res = np.where(idx, 1000, o)
print(res)


[[False  True False  True]
 [False  True  True  True]
 [ True  True  True  True]]
[[   2 1000    3 1000]
 [   1 1000 1000 1000]
 [1000 1000 1000 1000]]


In [75]:

d = r%2 == 0
print(d)

print()
r[d] = 10000000
print(r)

r[2,2] = -1
print(r)

[[False  True False  True]
 [False  True  True  True]
 [ True  True  True  True]]

[[       5 10000000        7 10000000]
 [       3 10000000 10000000 10000000]
 [10000000 10000000 10000000 10000000]]
[[       5 10000000        7 10000000]
 [       3 10000000 10000000 10000000]
 [10000000 10000000       -1 10000000]]


In [84]:
np.ones(10, dtype=np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [83]:
r = np.ones((2,3,4))
print(r)
print(r.ndim)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3


In [87]:
rd = np.random.randint(10,100,size=10) 
print(rd)
rd = np.random.randint(10,100,size=(2,3)) 
print(rd)

[75 63 40 21 21 35 50 45 42 15]
[[25 49 76]
 [68 93 71]]


In [3]:
import numpy as np

r=np.arange(12,0,-1).reshape(4,3)
idx = r %2 == 0
print(idx)
print(~idx)

print(np.where(idx))
print(np.where(~idx))

[[ True False  True]
 [False  True False]
 [ True False  True]
 [False  True False]]
[[False  True False]
 [ True False  True]
 [False  True False]
 [ True False  True]]
(array([0, 0, 1, 2, 2, 3]), array([0, 2, 1, 0, 2, 1]))
(array([0, 1, 1, 2, 3, 3]), array([1, 0, 2, 1, 0, 2]))
