In [ ]:
# linspace
# any, all
# T
# isna /isnull
# reshape / resize

In [1]:
import numpy as np

In [8]:
a1 = np.arange(10,20)
print(a1)

print()
a2 = np.linspace(10, 19, 10)
print(a2)
a2 = np.linspace(10, 19, 40)
print(a2)

[10 11 12 13 14 15 16 17 18 19]

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[10.         10.23076923 10.46153846 10.69230769 10.92307692 11.15384615
 11.38461538 11.61538462 11.84615385 12.07692308 12.30769231 12.53846154
 12.76923077 13.         13.23076923 13.46153846 13.69230769 13.92307692
 14.15384615 14.38461538 14.61538462 14.84615385 15.07692308 15.30769231
 15.53846154 15.76923077 16.         16.23076923 16.46153846 16.69230769
 16.92307692 17.15384615 17.38461538 17.61538462 17.84615385 18.07692308
 18.30769231 18.53846154 18.76923077 19.        ]


In [14]:
a = np.arange(15).reshape(3,5) # retruns a view
print(a)

print()
#a = np.arange(15).reshape(4,5) #  15=>20 # this doesn't  work
a = np.arange(15) # modifies original one. Doesn't create a copy or any view
a.resize(4,5) # 15=>20 
print(a)

print()
a = np.arange(15)
a.resize(3,4) # 15=>12
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  0  0  0  0]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [46]:
a1 = np.arange(15).reshape(5,3)
#a2 = a1.reshape(3,5)
print(a1)
#print(a2)

# 1 2 3 4 5 6

a1.resize(10,20)
print()
a1[0] = 100
#a2[2,3] = 300
print(a1)
#print(a2)

print(a1.sum())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


ValueError: cannot resize this array: it does not own its data

In [34]:
a = np.arange(15).reshape(3,5)
print(a)

print()
print(a.sum())

print()
print(a.sum(axis = 0))

print()
print(a.sum(axis = 1))

print(a.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

105

[15 18 21 24 27]

[10 35 60]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [33]:
a = np.array([1,2,3, np.nan])
print(a)

print(a.sum())
print(1 + np.nan)
print(1 / np.nan)
print(np.nan == np.nan)
print(np.nan != np.nan)
print(np.nan < np.nan)
print(np.nan > np.nan)

print()
print(np.isnan(a))

[ 1.  2.  3. nan]
nan
nan
nan
False
True
False
False

[False False False  True]


In [31]:
a = np.array(["c", "bcd", "pwr", "1"])
print(a)
print(a.dtype)

['c' 'bcd' 'pwr' '1']
<U3


In [38]:
a = np.arange(10)
print(a.shape)
print(a.T.shape)

a1 = a.reshape(10,1)
print(a1.shape)
print(a1)

(10,)
(10,)
(10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
