In [1]:
# all imports go at the top, even though python is a very open language
import pandas as pd
import numpy as np

In [2]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p14', '_np_version_under1p15', '_np_version_under1p16', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_versio

In [3]:
print(dir(pd.DataFrame))

['T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul

## Series

In [29]:
# Normal series and series with custom index
s1 = pd.Series([1,2,3])
s2 = pd.Series([1,2,3, np.nan], index=list("abcd"))
print(s1)
print()
print(s2)

0    1
1    2
2    3
dtype: int64

a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64


In [14]:
# changing dtype: astype
r=s2.astype("str")
print(r)
print(r.values)

# make sure no nan data is there before astype
print()
r = s2.fillna(0)
print(r)
r  = r.astype(np.int8)
print(r)

a    1.0
b    2.0
c    3.0
d    nan
dtype: object
['1.0' '2.0' '3.0' 'nan']

a    1.0
b    2.0
c    3.0
d    0.0
dtype: float64
a    1
b    2
c    3
d    0
dtype: int8


In [7]:
# shape, size, dtype, index, values
print(s1.shape)
print(s1.size)
print(s1.dtype)
print(s1.index)
print(s1.values)

print()
print(s2.shape)
print(s2.size)
print(s2.dtype)
print(s2.index)
print(s2.values)

(3,)
3
int64
RangeIndex(start=0, stop=3, step=1)
[1 2 3]

(4,)
4
float64
Index(['a', 'b', 'c', 'd'], dtype='object')
[ 1.  2.  3. nan]


In [17]:
# aggregate operations: min, max, unique, sum etc.

print(s1.min())
print(s2.min())
print(s1.unique())

1
1.0
[1 2 3]


In [ ]:
# arithmetic operations(new copy) and broadcast like numpy

In [25]:
# indexing and slicing
print(s1)

print()
print(s1[0])

print()
print(s1[::2])

print()
idx = s1 % 2 == 0
print(idx)
print(s1[idx])

print()
print(s1[[1,2]])

0    1
1    2
2    3
dtype: int64

1

0    1
2    3
dtype: int64

0    False
1     True
2    False
dtype: bool
1    2
dtype: int64

1    2
2    3
dtype: int64


In [30]:
# result of operations as index
sc = s1.copy()
print(sc)
print()

sc[0] = 100
print(sc)

sc[1:] = 200
print(sc)

0    1
1    2
2    3
dtype: int64

0    100
1      2
2      3
dtype: int64
0    100
1    200
2    200
dtype: int64


In [33]:
# frequency : value_counts
sc.value_counts()

200    2
100    1
dtype: int64

## DataFrame

In [34]:
# dataframe from dict or list of rows
df1 = pd.DataFrame(
    {
        "Name":   ["Gaurav", "Abhishek1", "Krishna", "Abhishek2", "Harshita", "Joey", "Shweta", "na-1" , "na-2"  , np.nan],
        "Age":    [ 0      , 1          , 2        , 2          , 1         , 2     , 3       , 1      ,  np.nan , 2     ],
        "Gender": [ 0      , 0          , 0        , 0          , 1         , 1     , 1       , np.nan ,  0      , 0     ]
    }
)
df2 = pd.DataFrame([("Gaurav",1), ("Abhiskek",2), ("Krishna",3), ("Abhishek2",4)],
                    index=[0,11,2,3], 
                    columns=["Name", "Number"])
print(df1)
print()
print(df2)

        Name  Age  Gender
0     Gaurav  0.0     0.0
1  Abhishek1  1.0     0.0
2    Krishna  2.0     0.0
3  Abhishek2  2.0     0.0
4   Harshita  1.0     1.0
5       Joey  2.0     1.0
6     Shweta  3.0     1.0
7       na-1  1.0     NaN
8       na-2  NaN     0.0
9        NaN  2.0     0.0

         Name  Number
0      Gaurav       1
11   Abhiskek       2
2     Krishna       3
3   Abhishek2       4


In [40]:
# shape, size, dtypes, index, columns, unique, T
print(df1.shape)
print(df1.size)
print()
print(df1.dtypes)
print(type(df1.dtypes))

print(df1.dtypes.unique())

(10, 3)
30

Name       object
Age       float64
Gender    float64
dtype: object
<class 'pandas.core.series.Series'>
[dtype('O') dtype('float64')]


In [45]:
# Rename index and columns on df2.
# Inplace vs normal operation
r = df1.rename({'Age':'A', 'Gender':1}, axis=1)
print(r)
print()
print(df1)



        Name    A    1
0     Gaurav  0.0  0.0
1  Abhishek1  1.0  0.0
2    Krishna  2.0  0.0
3  Abhishek2  2.0  0.0
4   Harshita  1.0  1.0
5       Joey  2.0  1.0
6     Shweta  3.0  1.0
7       na-1  1.0  NaN
8       na-2  NaN  0.0
9        NaN  2.0  0.0

        Name  Age  Gender
0     Gaurav  0.0     0.0
1  Abhishek1  1.0     0.0
2    Krishna  2.0     0.0
3  Abhishek2  2.0     0.0
4   Harshita  1.0     1.0
5       Joey  2.0     1.0
6     Shweta  3.0     1.0
7       na-1  1.0     NaN
8       na-2  NaN     0.0
9        NaN  2.0     0.0


In [44]:
r = df1.rename(columns={'Age':'A'})
print(r)
print()
print(df1)

        Name    A  Gender
0     Gaurav  0.0     0.0
1  Abhishek1  1.0     0.0
2    Krishna  2.0     0.0
3  Abhishek2  2.0     0.0
4   Harshita  1.0     1.0
5       Joey  2.0     1.0
6     Shweta  3.0     1.0
7       na-1  1.0     NaN
8       na-2  NaN     0.0
9        NaN  2.0     0.0

        Name  Age  Gender
0     Gaurav  0.0     0.0
1  Abhishek1  1.0     0.0
2    Krishna  2.0     0.0
3  Abhishek2  2.0     0.0
4   Harshita  1.0     1.0
5       Joey  2.0     1.0
6     Shweta  3.0     1.0
7       na-1  1.0     NaN
8       na-2  NaN     0.0
9        NaN  2.0     0.0


In [53]:
r = df1.rename(columns={'Age':'A', "Gender": 999}, inplace=True) # don't need to store inside r
print(r)
print()
print(df1)

None

        Name    A  999
0     Gaurav  0.0  0.0
1  Abhishek1  1.0  0.0
2    Krishna  2.0  0.0
3  Abhishek2  2.0  0.0
4   Harshita  1.0  1.0
5       Joey  2.0  1.0
6     Shweta  3.0  1.0
7       na-1  1.0  NaN
8       na-2  NaN  0.0
9        NaN  2.0  0.0


In [ ]:
pd.read_sql_query()

In [55]:
# Indexing columns directly and via index.
print(df1)
print(df1.Name)


        Name    A  999
0     Gaurav  0.0  0.0
1  Abhishek1  1.0  0.0
2    Krishna  2.0  0.0
3  Abhishek2  2.0  0.0
4   Harshita  1.0  1.0
5       Joey  2.0  1.0
6     Shweta  3.0  1.0
7       na-1  1.0  NaN
8       na-2  NaN  0.0
9        NaN  2.0  0.0
0       Gaurav
1    Abhishek1
2      Krishna
3    Abhishek2
4     Harshita
5         Joey
6       Shweta
7         na-1
8         na-2
9          NaN
Name: Name, dtype: object


In [57]:
print(df1)
print()
print(df1["Name"])

        Name    A  999
0     Gaurav  0.0  0.0
1  Abhishek1  1.0  0.0
2    Krishna  2.0  0.0
3  Abhishek2  2.0  0.0
4   Harshita  1.0  1.0
5       Joey  2.0  1.0
6     Shweta  3.0  1.0
7       na-1  1.0  NaN
8       na-2  NaN  0.0
9        NaN  2.0  0.0

0       Gaurav
1    Abhishek1
2      Krishna
3    Abhishek2
4     Harshita
5         Joey
6       Shweta
7         na-1
8         na-2
9          NaN
Name: Name, dtype: object


In [71]:
a = np.arange(12).reshape(3,4)
print(a)

print(type(a[1][1]))
print(type(a[1]), a[1])
print(type(a[1:4]), a[1:4])

print()
print(type(a[1:2,1:2]), a[1:2,1:2])
print(type(a[1][1:2]), a[1][1:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
<class 'numpy.int64'>
<class 'numpy.ndarray'> [4 5 6 7]
<class 'numpy.ndarray'> [[ 4  5  6  7]
 [ 8  9 10 11]]

<class 'numpy.ndarray'> [[5]]
<class 'numpy.ndarray'> [5]


In [60]:
print(df1)
print()
print(df1[999])
# print(df1.999)

        Name    A  999
0     Gaurav  0.0  0.0
1  Abhishek1  1.0  0.0
2    Krishna  2.0  0.0
3  Abhishek2  2.0  0.0
4   Harshita  1.0  1.0
5       Joey  2.0  1.0
6     Shweta  3.0  1.0
7       na-1  1.0  NaN
8       na-2  NaN  0.0
9        NaN  2.0  0.0

0    0.0
1    0.0
2    0.0
3    0.0
4    1.0
5    1.0
6    1.0
7    NaN
8    0.0
9    0.0
Name: 999, dtype: float64


In [62]:
print(df1[3:9])

        Name    A  999
3  Abhishek2  2.0  0.0
4   Harshita  1.0  1.0
5       Joey  2.0  1.0
6     Shweta  3.0  1.0
7       na-1  1.0  NaN
8       na-2  NaN  0.0


In [64]:
# Series in a DataFrame
print(type(df1.Name))

<class 'pandas.core.series.Series'>


In [ ]:
# describe, top/bottom rows of data

In [ ]:
# indexing and slicing
# loc, iloc [rows, cols]

In [ ]:
# aggregate operations (with and without axis : row-1, col-0)
# min, max, count, ...

In [ ]:
# arithmetic operations

In [ ]:
# Na Values: isna, fillna, dropna

In [ ]:
# any, all

In [ ]:
# ordering data, sort_values

In [ ]:
# row / column wise operation: apply
tmp = pd.DataFrame(np.random.randint(10,20,20).reshape(5,4))

In [ ]:
# str submodule (replace etc)

In [ ]:
# load and save data

In [ ]:
# groups: groupby

In [ ]:
# groups and aggregates