In [2]:
#1.create a numpy array of 5 zeros.
#check datatype, itemsize and shape of above
import numpy as np
x = np.zeros(5, dtype = int)
print(x,type(x))
print()
print(x.dtype)
print()
print(x.itemsize)
print()
print(x.shape)

[0 0 0 0 0] <class 'numpy.ndarray'>

int32

4

(5,)


In [3]:
#2.create a numpy array of ones of shape (5,4)
x1 = np.ones((5,4),dtype = int)
print(x1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
#3.create a matrix of shape 4,5 with numbers from 1-20
x2 = np.arange(1,21)
x3 = x2.reshape(4,5)
print(x3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
#4.multiply all elements of above array by 10
print(x3*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [6]:
#5.print odd elements from array
#n = np.array([])
for i in range(1,len(x2)):
    if i % 2 !=0:
        print(i)

1
3
5
7
9
11
13
15
17
19


In [7]:
#6.replace all even elements by their negative
for j in range(1,len(x2)+1):
    if j % 2 == 0:
        print(-j)

-2
-4
-6
-8
-10
-12
-14
-16
-18
-20


In [8]:
#7.create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1 = np.linspace(1,17,num=16).reshape(4,4)
print(M1)

[[ 1.          2.06666667  3.13333333  4.2       ]
 [ 5.26666667  6.33333333  7.4         8.46666667]
 [ 9.53333333 10.6        11.66666667 12.73333333]
 [13.8        14.86666667 15.93333333 17.        ]]


In [9]:
#8. create a transpose of above matrix call it M2
M2 = M1.T
print(M2)

[[ 1.          5.26666667  9.53333333 13.8       ]
 [ 2.06666667  6.33333333 10.6        14.86666667]
 [ 3.13333333  7.4        11.66666667 15.93333333]
 [ 4.2         8.46666667 12.73333333 17.        ]]


In [10]:
#9. find sum of above matrix M3 = (M1 + M2)
M3 = M1 + M2
print(M3)

[[ 2.          7.33333333 12.66666667 18.        ]
 [ 7.33333333 12.66666667 18.         23.33333333]
 [12.66666667 18.         23.33333333 28.66666667]
 [18.         23.33333333 28.66666667 34.        ]]


In [11]:
#10.Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.T
if M3.all() == MT1.all():
    print(True)

True


In [12]:
#11. find diffrence of M4 = (M1 - M2)
M4 = M1 - M2
print(M4)

[[ 0.  -3.2 -6.4 -9.6]
 [ 3.2  0.  -3.2 -6.4]
 [ 6.4  3.2  0.  -3.2]
 [ 9.6  6.4  3.2  0. ]]


In [13]:
#12. Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = M4.T
if M4.all() == MT2.all():
    print(True)

True


In [14]:
#13. create a matrix (3x4) R1 of random numbers between 10-40
import random
R1 = np.random.randint(10,40,size =12).reshape(3,4)
print(R1)


[[11 25 21 34]
 [10 27 33 22]
 [29 23 30 28]]


In [15]:
#14.find min and max column wise
# Row wise
print(R1.max(axis = 1)) 
print(R1.min(axis = 1)) 
print()
# column wise
print(R1.max(axis = 0))
print(R1.min(axis = 0))


[34 33 30]
[11 10 23]

[29 27 33 34]
[10 23 21 22]


In [16]:
#15. replace the last column with sum of all the columns
#R1[:,-1] = 
#print(R2)
R1[:,-1] = R1.sum()
print(R1)

[[ 11  25  21 293]
 [ 10  27  33 293]
 [ 29  23  30 293]]


In [17]:
#16.create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,size = 12).reshape(3,4)
print(R1)

[[15 29 22 21]
 [21 15 25 18]
 [32 12 35 14]]


In [18]:
#17. replace all even elements with nan in R1
R1 = R1.astype('float') #np.nan has type float
i = R1 % 2 == 0
R1[i] = 'Nan'
print(R1)

[[15. 29. nan 21.]
 [21. 15. 25. nan]
 [nan nan 35. nan]]


In [19]:
#18.count number of nan in R1
print(np.count_nonzero(np.isnan(R1)))

5


In [23]:
#19.check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
