## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


## create a numpy array of 5 zeros.
check datatype, itemsize and shape of above

In [2]:
import numpy as np

nArray = np.array([0]*5)
print("Array", nArray)
print("Type", nArray.dtype)
print("Size", nArray.size)
print("Shape", nArray.shape)

Array [0 0 0 0 0]
Type int64
Size 5
Shape (5,)


## create a numpy array of ones of shape (5,4)

In [3]:
nArray = np.ones((5,4),dtype=int)
print(nArray)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## create a matrix of shape 4,5 with numbers from 1-20

In [54]:
nArray = np.arange(1,21).reshape(4,5)
print(nArray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## multiply all elements of above array by 10

In [5]:
nArray_Mul_10 = nArray*10
print(nArray_Mul_10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


## print odd elements from array

In [6]:
print(nArray[nArray%2!=0])

[ 1  3  5  7  9 11 13 15 17 19]


## replace all even elements by their negative

In [7]:
even = nArray%2 == 0
nArray[even] = -(nArray[even])
print(nArray)

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


## create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

In [18]:
M1 = np.linspace(1,16, num=16, endpoint=True).reshape(4,4)
print("M1:\n", M1)

M1:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


## create a transpose of above matrix call it M2

In [19]:
M2 = M1.T
print("M2:\n", M2)

M2:
 [[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


## find sum of above matrix M3 = (M1 + M2)

In [20]:
M3 = M1 + M2
print("M3:\n", M3)

M3:
 [[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


## Find Transpose of M3, Call it MT1. Check if M3 == MT1

In [31]:
MT1 = M3.T
print("MT1:\n", MT1)

if (M3 == MT1).all():
    print("M3 is equal to MT1.")
else:
    print("M3 is not equal to MT1.")

MT1:
 [[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]
M3 is equal to MT1.


## find diffrence of M4 = (M1 - M2)

In [22]:
M4 = M1 - M2
print("M4:\n", M4)

M4:
 [[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


## Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

In [32]:
MT2 = M4.T
print("MT2:\n", MT2)

print()
if (M4 == MT2).all():
    print("M4 is equal to MT2")
else:
    print("M4 is not equal to MT2.")

print()
if (M4 == -MT2).all():
    print("M4 is equal to -MT2")
else:
    print("M4 is not equal to -MT2.")


MT2:
 [[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]

M4 is not equal to MT2.

M4 is equal to -MT2


## create a matrix (3x4) R1 of random numbers between 10-40

In [106]:
import random
R1 = np.array(random.sample(range(10, 40),12)).reshape(3,4)
print("R1:\n", R1)

R1:
 [[19 25 10 26]
 [39 18 38 30]
 [29 21 17 35]]


## find min and max column wise

In [107]:
print("Min of R1: ", R1.min())
print("Max of R1: ", R1.max())

Min of R1:  10
Max of R1:  39


## replace the last column with sum of all the columns

In [108]:
print("R1:\n", R1)
R1[:,-1] = R1.sum(axis = 1)
print("R1:\n", R1)

R1:
 [[19 25 10 26]
 [39 18 38 30]
 [29 21 17 35]]
R1:
 [[ 19  25  10  80]
 [ 39  18  38 125]
 [ 29  21  17 102]]


## create a matrix (3x4) R1 of random numbers between 10-40

In [151]:
R1 = np.array(random.sample(range(10,40),12), dtype="float").reshape(3,4)
print("R1:\n", R1)

R1:
 [[38. 28. 11. 21.]
 [30. 10. 12. 34.]
 [36. 18. 23. 24.]]


## replace all even elements with nan in R1

In [153]:
Even = R1[::]%2==0
R1[Even] = np.NaN
print(R1)

[[nan nan 11. 21.]
 [nan nan nan nan]
 [nan nan 23. nan]]


## count number of nan in R1

In [163]:
No_of_NaN = np.count_nonzero(np.isnan(R1))
print("Number of NaN in array: ", No_of_NaN)

Number of NaN in array:  9


## check output of this code
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`

In [164]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
