In [1]:
import numpy as np

In [2]:
#1 create a numpy array of 5 zeros.
#check datatype, itemsize and shape of above

z = np.zeros(5)
print(z)
print("data type of array ", z, ":", z.dtype)
print("item size of array ", z, ":", z.itemsize)
print("number of dimensions   \t\t\t  :", z.ndim)
print("total no. of elements: \t\t\t  :",z.size)
print("data type of array ", z, ":", z.shape)

[0. 0. 0. 0. 0.]
data type of array  [0. 0. 0. 0. 0.] : float64
item size of array  [0. 0. 0. 0. 0.] : 8
number of dimensions   			  : 1
total no. of elements: 			  : 5
data type of array  [0. 0. 0. 0. 0.] : (5,)


In [3]:
#2 create a numpy array of ones of shape (5,4)
arr_ones = np.ones((5,4))  # 2-D 
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
#3 create a matrix of shape 4,5 with numbers from 1-20

m1 = np.arange(1,21).reshape(4,5)
print(m1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
#4 multiply all elements of above array by 10
print(m1 * 10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [6]:
#5 print odd elements from array in #3
print(m1)
print()
idx = m1%2 != 0
print(idx)       # boolean index , marks elements True if they are not divisible by 2 otherwise False 
print()
print("All odd elements from array : ", m1[idx])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]

All odd elements from array :  [ 1  3  5  7  9 11 13 15 17 19]


In [7]:
#6 replace all even elements by their negative ( continue from #5 )
print(m1)
print()
print(~idx)       # boolean index , marks elements True if they are not divisible by 2 otherwise False 
print()
# print("All odd elements from array : ", m1[idx])
m1[~idx]=-m1[~idx]
print("All even elements by their negative value : ", m1[~idx])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]

All even elements by their negative value :  [ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


In [8]:
#7 create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
a = np.linspace(1,16,16) # start, stop, num=16
M1 = a.reshape(4,4)
print(M1)          # 2-D array 
# m2 = np.linspace(1,16,16).reshape(4,4)
# print(m2)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [9]:
#8 create a transpose of above matrix call it M2
M2 = M1.T
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [10]:
#9 find sum of above matrix M3 = (M1 + M2)

M3 = M1 + M2
print(M1)
print()
print(M2)
print()
print(M3)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [11]:
# 10 Find Transpose of M3, Call it MT1. Check if M3 == MT1

MT1 = M3.T
print(M3)
print()
print(MT1)

idx = MT1 == M3
print()
print(idx)
print()
if np.ndarray.all(idx):               # Returns True if all elements evaluate to True
    print("Both MT1 and M3 are equal")
else:
    print("Both MT1 and M3 are not equal")


[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

Both MT1 and M3 are equal


In [12]:
# 11 find diffrence of M4 = (M1 - M2)

print(M1)
print()
print(M2)
print()
M4 = M1 - M2
print(M4)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [13]:
#12a Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

MT2 = M4.T

print(M4)
print()
print(MT2)
print()
d = M4 == MT2
print(d)

print()
if np.ndarray.all(d):
    print("Both M4 and MT2 are equal")
else:
    print("Both M4 and MT2 are not equal")

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]

[[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

Both M4 and MT2 are not equal


In [14]:
#12b Find Transpose of M4, Call it MT2. check if M4 == -MT2

print(M4)
print()
print(-MT2)
print()
d1 = M4 == -MT2
print(d1)

print()
if np.ndarray.all(d1):
    print("Both M4 and -MT2 are equal")
else:
    print("Both M4 and -MT2 are not equal")

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]

[[-0. -3. -6. -9.]
 [ 3. -0. -3. -6.]
 [ 6.  3. -0. -3.]
 [ 9.  6.  3. -0.]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

Both M4 and -MT2 are equal


In [51]:
#13 create a matrix (3x4) R1 of random numbers between 10-40

R1 = np.random.randint(10,40, size=(3,4))
print(R1)

[[32 26 31 36]
 [17 30 11 24]
 [13 35 37 13]]


In [52]:
# 14 find min and max column wise for R1
print("Max for each column: " , R1.max(axis=0))
print()
print("Min for each column: ", R1.min(axis=0))

Max for each column:  [32 35 37 36]

Min for each column:  [13 26 11 13]


In [53]:
# 15 replace the last column with sum of all the columns
print("........R1........ ")
print(R1)
print("Shape of array : ", R1.shape)
s1 = R1.sum(axis=0)
print()
print("Sum of each Column: ", s1)
print()
s2 = R1.sum(axis=1)
print("Sum of each Row: ", s2)
# print(R1[:,3])
rows = len(R1)
cols = len(R1[0])
# print(rows)
# print(cols)
R1[:,cols-1] = s2  # replacing the last column with the sum 
print()
print(R1)

........R1........ 
[[32 26 31 36]
 [17 30 11 24]
 [13 35 37 13]]
Shape of array :  (3, 4)

Sum of each Column:  [62 91 79 73]

Sum of each Row:  [125  82  98]

[[ 32  26  31 125]
 [ 17  30  11  82]
 [ 13  35  37  98]]


In [42]:
#16 create a matrix (3x4) R2 of random numbers between 10-40
# replace all even elements with nan in R1
# count number of nan in R1

R2 = np.random.randint(10,40, size=(3,4))
print(R2)
R2 = R2.astype('float') # np.nan has type float: arrays also should have either float datatype / complex / object
                        #so cast arr before you try to assign this value. 
print()
print(R2)

idx = R2%2 == 0
print()
# print(idx)
# print()
R2[idx] = 'Nan'
print(R2)

print()
# print(np.isnan(R1))
# print()

print("Number of Nan in R2 = ", np.count_nonzero(np.isnan(R2)))

[[21 21 10 39]
 [32 11 24 38]
 [12 39 30 14]]

[[21. 21. 10. 39.]
 [32. 11. 24. 38.]
 [12. 39. 30. 14.]]

[[21. 21. nan 39.]
 [nan 11. nan nan]
 [nan 39. nan nan]]

Number of Nan in R2 =  7


In [19]:
#17 check output of this code
a1 = np.arange(1,10).reshape(3,3)
print(a1)
print()
a2 = np.arange(11,20).reshape(3,3)
print(a2)
print()
a3 = np.append(a1,a2)
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
