In [11]:
import numpy as np
a=np.array([0,0,0,0,0])
print(a)

print(a.dtype)
print(a.size)
print(a.shape)

[0 0 0 0 0]
int32
5
(5,)


In [20]:
b=np.ones((5,4), dtype=np.int64)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [33]:

# create a matrix of shape 4,5 with numbers from 1-20
arr=np.arange(1,21).reshape(4,5)
print(arr)

a=np.arange(1,21,1).reshape(5,4)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [35]:
r=a*10
print(r)
print(a)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]
 [170 180 190 200]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [39]:
print(a)

o=a%2==1

e=a%2==0
print(a[o])

print(~a[o])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 1  3  5  7  9 11 13 15 17 19]
[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


In [46]:
m1=np.linspace(1,16, num=16,dtype=int).reshape(4,4)
print(m1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [45]:
m2=a.T
print(m2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [47]:
m3=m1+m2
print(m3)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [52]:
mt1=m3.T
print(mt1)

if mt1.all()==m3.all():
    print("Equal")

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]
Equal


In [59]:
m4=m1-m2
print(m4)

print()
mt2=m4.T
print(mt2)

print(m4==mt2)
print(m4==-mt2)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [68]:
b=np.random.randint(10,40,size=(3,4))
print(b)
print()

print(b.min(axis=0))
print(b.max(axis=0))

[[29 26 31 18]
 [18 31 34 27]
 [21 39 23 14]]

[18 26 23 14]
[29 39 34 27]


In [82]:
b=np.random.randint(10,40,size=(3,4))
print(b)

e=b%2==0

print()
b=b.astype("float")
b[e]=np.nan
print(b)
print()
c=np.count_nonzero(np.isnan(b))
print(c)

[[34 26 22 35]
 [30 30 17 11]
 [14 19 19 15]]

[[nan nan nan 35.]
 [nan nan 17. 11.]
 [nan 19. 19. 15.]]

6


In [87]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
#1-9
a2 = np.arange(11,20).reshape(3,3)
#11-19
print(a2)
a3 = np.append(a1,a2)
print(a3)
#sum??
#a4=np.append()

print()

a3 = np.append(a1,a2, axis = 0)
print(a3)

print()
a3 = np.append(a1,a2, axis = 1)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
