In [20]:
import numpy as np

In [38]:
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above
arr=np.array([0]*5)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.size)
print(arr.shape)

[0 0 0 0 0]
<class 'numpy.ndarray'>
int32
5
(5,)


In [39]:
# create a numpy array of ones of shape (5,4)
arr=np.ones((5,4),dtype=int)
print(arr)
print(arr.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(5, 4)


In [40]:
# create a matrix of shape 4,5 with numbers from 1-20
arr=np.arange(1,21).reshape(4,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [41]:
# multiply all elements of above array by 10
print(arr*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [42]:
# print odd elements from array
odd = arr%2==1
print(arr[odd])

[ 1  3  5  7  9 11 13 15 17 19]


In [43]:
# replace all even elements by their negative
arr[~odd]=-arr[~odd]
print(arr)

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [44]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
m1=np.linspace(1,16,num=16,endpoint=True).reshape(4,4)
print(m1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [47]:
# create a transpose of above matrix call it M2
m2=m1.T
print(m2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [48]:
# find sum of above matrix M3 = (M1 + M2)
m3=m1+m2
print(m3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [49]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
mt1=m3.T
print(m3==mt1)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [51]:
# find diffrence of M4 = (M1 - M2)
m4=m1-m2
print(m4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [55]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
mt2=m4.T
print(m4==mt2)
print(m4==-mt2)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [73]:
# create a matrix (3x4) R1 of random numbers between 10-40
r1=np.random.randint(10,40,size=(3,4))
print(r1)

[[36 23 31 32]
 [26 21 21 16]
 [26 18 37 36]]


In [74]:
# find min and max column wise
print(r1.min(axis=0))
print(r1.max(axis=0))

[26 18 21 16]
[36 23 37 36]


In [75]:
# replace the last column with sum of all the columns
print(r1.sum(axis=1))
print(r1[:,3])
r1[:,3]=r1.sum(axis=1)
print()
print(r1)

[122  84 117]
[32 16 36]

[[ 36  23  31 122]
 [ 26  21  21  84]
 [ 26  18  37 117]]


In [95]:
# create a matrix (3x4) R1 of random numbers between 10-40
r1=np.random.randint(10,40,size=(3,4))
print(r1)

[[31 33 33 33]
 [20 13 25 32]
 [35 30 30 24]]


In [96]:
# replace all even elements with nan in R1
ev=r1%2==0
r1[ev]=-99999
print(r1)

[[    31     33     33     33]
 [-99999     13     25 -99999]
 [    35 -99999 -99999 -99999]]


In [107]:
# count number of nan in R1
n=r1+99999==0
print(np.where(n)[0].size)

5


In [108]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
